all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: pi
    ansible_become: true
    security_mode: plaintext
    confluent:
      support:
        metrics_enabled: false
    kafka:
      broker:
        environment:
          KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
          JMX_PORT: 30000
        config:
          offsets.topic.replication.factor: 2
          transaction.state.log.min.isr: 1
          transaction.state.log.replication.factor: 2
          confluent.metrics.reporter.topic.replicas: 2


preflight:
  hosts:
    10.0.0.120:
    10.0.0.77:
zookeeper:
  hosts:
    10.0.0.120:
broker:
  hosts:
    10.0.0.120:
      kafka:
        broker:
          id: 101
          config:
            advertised.listeners: PLAINTEXT://10.0.0.120:9092

    10.0.0.77:
      kafka:
        broker:
          id: 102
          config:
            advertised.listeners: PLAINTEXT://10.0.0.77:9092

